source 'https://rubygems.org'
# gem 'teamwork', git: 'https://github.com/ehalferty/teamwork', branch: 'master'
gem 'faraday'
gem 'faraday_middleware'
gem 'json'
gem 'activesupport','~> 5.2.3', require: 'active_support/all'
gem 'pry'